### ISSUE TITLE
Docker stays slow. Wrong shared directory?

### ISSUE THREAD

**Issue by peterfication** [brikis98/docker-osx-dev#108]
I tried to get docker-osx-dev to work but I had no success.
## Dockerfile

```
FROM ruby:2.1.5

RUN apt-get update && apt-get install -y \
  build-essential \
  nodejs

ENV RAILS_ROOT /rails_root
RUN mkdir -p $RAILS_ROOT

COPY Gemfile $RAILS_ROOT/
COPY Gemfile.lock $RAILS_ROOT/

WORKDIR $RAILS_ROOT
RUN gem install bundler && bundle install --jobs 20 --retry 5

COPY . $RAILS_ROOT/

EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
```
## docker-compose.yml

```
web:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - .:/rails_root
  links:
    - postgres_db:postgres
  environment:
    POSTGRES_URL: postgres://postgres-db:5432
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: secret

postgres_db:
  image: postgres
  hostname: postgres-db
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: secret
```

If I remove the volumes part in `docker-compose.yml` the server is fast as expected. If I don't remove it, the server is slow as expected. If I run `docker-osx-dev` all the sync stuff is happening. But the server stays slow.

I get the following debugging output:

```
2015-09-13 20:38:48 [INFO] Performing initial sync of paths: /Users/username/ruby/rails-project
2015-09-13 20:38:48 [DEBUG] Creating parent directories in Docker VM: sudo mkdir -p /Users/username/ruby && sudo chown -R docker /Users/username/ruby
2015-09-13 20:39:28 [DEBUG] Starting sync paths: /Users/username/ruby/rails-project
```

I thought, that `docker-osx-dev` is syncing the local dir with the dir specified in `docker-compose.yml` (`/rails_root`) or did I get something wrong?

If this behaviour is correct I don't know where to look for an error. Might anyone has a hint for me?
