### ISSUE TITLE
Ports from docker-compose.yml not forwarded to host

### ISSUE THREAD

**Issue by jon-armstrong-zz** [brikis98/docker-osx-dev#130]
I have a docker-compose setup similar to the following:

```
users:
   image: myimage
   ports:
     - "3001:3001"
```

According to the docker-compose docs, I was expecting this to forward to the host, but instead it only forwards 3001 to the boot2docker VM. Does docker-osx-dev set up forwarding, or do I need to configure it manually?
