### ISSUE TITLE
How can you confirm everything is working properly?

### ISSUE THREAD

**Issue by schlenks** [brikis98/docker-osx-dev#161]
First off, this looks like an incredible project. I've been trying to improve the speed of my docker environment and figured it was due to the performance hit of virtualbox filesharing.

However, after following the setup setups, running docker-osx-dev in one terminal and then running docker-compose up in another (and letting docker-osx-dev finish syncing) I am not seeing any change in initial boot or initial load times.

Ie,
under vanilla docker setup, it takes about 1m15s to load the apps homepage. Under docker-osx-dev it takes about the same. 
When I loaded up the same app in dinghy (so it uses NFS), it loads in about 39s

Given that rsync _should_ be about 2x-3x faster than NFS, I think your project should bring the load times down to near native filesystem, which is exciting. If there's anything I'm missing or anything I can provide, more than happy to. 

This is how I created the initial docker-machine:

```
docker-machine create --driver virtualbox --virtualbox-memory 5120 --virtualbox-disk-size 30000 --virtualbox-cpu-count 2 --virtualbox-no-share default
```

This is my dockerfile:

```
FROM ruby:2.2.3

ENV APP_HOME /app

RUN apt-get update -qq && apt-get install -y build-essential nodejs apt-utils

RUN mkdir $APP_HOME
WORKDIR $APP_HOME

COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

COPY . ./
```

and this is my docker-compose.yml file:

```
web: &app_base
  build: .
  volumes:
    - .:/app
  command: bundle exec rails server -b 0.0.0.0 -p 3000
  environment: &app_environment
    # Run the app in the 'development' environment:
    RACK_ENV: development
    RAILS_ENV: development
    ENABLE_DEBUG_SERVER: "true"
  links:
    - db
    - redis
    - mailcatcher
  ports:
    - "8989:8989"

db:
  build: mysql_build
  hostname: app_db
  ports:
    - "3306:3306" # allows connections via workbench without host interference
  environment:
    MYSQL_ROOT_PASSWORD: notarealpassword

# alpine based version to keep it tiny
redis:
  image: tenstartups/alpine-redis
  expose:
    - "6379"

nginx:
  build: nginx_build
  ports:
    - "80:80"
    - "443:443"
  links:
    - web

mailcatcher:
  image: tophfr/mailcatcher
  ports:
    - "1080:80"
    - "1025:25"
```
